# Jobs details below. Common job params listed at the bottom of this file.
jobs:
  examples/ex1_full_sql_job.sql:  # shows 100% sql job, easiest when sql is enough
    py_job: 'core/sql_job.py'
    inputs:
      some_events: {'path':"{base_path}/wiki_example/inputs/{latest}/events_log.csv.gz", 'type':'csv'}
      other_events: {'path':"{base_path}/wiki_example/inputs/{latest}/events_log.csv.gz", 'type':'csv'}
    output: {'path':'{base_path}/wiki_example_sql/output_ex1_full_sql/{now}/', 'type':'csv'}
    frequency: 1 day
    start_date: "{today}T07:00:00"
    owners: ['some_email@address.com']

  examples/ex1_frameworked_job.py:  # shows frameworked pyspark ops, same as ex1_full_sql_job but gives access to spark ops to expand on sql.
    inputs:
      some_events: {'path':"{base_path}/wiki_example/inputs/{latest}/events_log.csv.gz", 'type':'csv'}
      other_events: {'path':"{base_path}/wiki_example/inputs/{latest}/events_log.csv.gz", 'type':'csv'}
    output: {'path':'{base_path}/wiki_example/output_ex1_frameworked/{now}/', 'type':'csv'}
    frequency: 1 day
    start_date: "{today}T07:00:00"
    owners: ['some_email@address.com']

  job_using_generic_template:  # to show how to reuse existing job code
    py_job: 'jobs/examples/ex1_frameworked_job.py'
    inputs:
      some_events: {'path':"{base_path}/wiki_example/inputs/{latest}/events_log.csv.gz", 'type':'csv'}
      other_events: {'path':"{base_path}/wiki_example/inputs/{latest}/other_events_log.csv.gz", 'type':'csv'}
    output: {'path':'{base_path}/wiki_example/output_ex1_frameworked_p2/{now}/', 'type':'csv'}

  examples/ex1_raw_job.py:
    frequency: 24h
    owners: ['some_email@address.com']

  examples/ex2_frameworked_job.py:  # more complex version of ex1_frameworked_job
    inputs:
      some_events: {'path':"{base_path}/wiki_example/inputs/{latest}/events_log.csv.gz", 'type':'csv'}
      other_events: {'path':"{base_path}/wiki_example/inputs/{latest}/events_log.csv.gz", 'type':'csv'}
    output: {'path':'{base_path}/wiki_example/output_ex2/{now}/', 'type':'csv'}
    frequency: 1 day
    start_date: "{today}T07:00:00"
    owners: ['some_email@address.com']

  examples/ex3_incremental_job.py:  # focus on incremental loading and dropping
    inputs:
      processed_events: {'path':"{base_path}/wiki_example/output_ex3_dep/{latest}/", 'type':'csv', 'inc_field': 'timestamp_obj'}
    output: {'path':'{base_path}/wiki_example/output_ex3_inc/incremental_build_v1/', 'type':'csv', 'inc_field': 'other_timestamp'}
    dependencies: [examples/ex3_incremental_prep_job.py]
    frequency: 24h
    owners: ['some_email@address.com']

  examples/ex3_incremental_prep_job.py:  # shows computation of dependency as necessary for ex3_incremental_job
    inputs:
      some_events: {'path':"{base_path}/wiki_example/inputs/{latest}/events_log.csv.gz", 'type':'csv'}
    output: {'path':'{base_path}/wiki_example/output_ex3_dep/{now}/', 'type':'csv'}
    frequency: 24h
    owners: ['some_email@address.com']

  examples/ex4_dependency1_job.py:  # shows dependency
    inputs:
      some_events: {'path':"{base_path}/wiki_example/inputs/{latest}/events_log.csv.gz", 'type':'csv'}
    output: {'path':'{base_path}/wiki_example/output_ex4_dep1/{now}/', 'type':'csv'}

  examples/ex4_dependency2_job.py:  # shows dependency without specifying inputs path since it is pulled from upstream.
    inputs:
      # some_events: {'from':'examples/ex4_dependency1_job.py'}
      some_events: {'path':'{base_path}/wiki_example/output_ex4_dep1/{latest}/', 'type':'csv', 'from':'examples/ex4_dependency1_job.py'}
    output: {'path':'{base_path}/wiki_example/output_ex4_dep2/{now}/', 'type':'csv'}
    dependencies: [examples/ex4_dependency1_job.py]

  examples/ex4_dependency3_job.sql:  # shows dependency with sql
    py_job: 'core/sql_job.py'
    inputs:
      some_events: {'path':'{base_path}/wiki_example/output_ex4_dep2/{latest}/', 'type':'csv', 'from':'examples/ex4_dependency2_job.py'}  # 'path' not needed when run as dependency
    output: {'path':'{base_path}/wiki_example/output_ex4_dep3/{now}/', 'type':'csv'}
    dependencies: [examples/ex4_dependency2_job.py, examples/ex4_dependency1_job.py]

  examples/ex4_dependency4_job.py:  # shows dependency
    inputs:
      some_events: {'path':'{base_path}/wiki_example/output_ex4_dep3/{latest}/', 'type':'csv', 'from':'examples/ex4_dependency3_job.sql'}
    output: {'path':'{base_path}/wiki_example/output_ex4_dep4/{now}/', 'type':'csv'}
    dependencies: [examples/ex4_dependency3_job.sql]

  examples/ex5_copy_to_oracle_job.py:  # shows frameworked pyspark ops, same as ex1_full_sql_job but gives access to spark ops to expand on sql.
    inputs:
      some_events: {'path':"{base_path}/wiki_example/inputs/{latest}/events_log.csv.gz", 'type':'csv'}
      other_events: {'path':"{base_path}/wiki_example/inputs/{latest}/other_events_log.csv.gz", 'type':'csv'}
    output: {'path':'{base_path}/wiki_example/output_ex5_copy_to_oracle/{now}/', 'type':'csv'}
    copy_to_oracle: {'creds': 'oracle', 'table': 'sandbox.test_ex5_pyspark_job'}

  examples/ex5_copy_to_redshift_job.py:  # shows frameworked pyspark ops, same as ex1_full_sql_job but gives access to spark ops to expand on sql.
    inputs:
      some_events: {'path':"{base_path}/wiki_example/inputs/{latest}/events_log.csv.gz", 'type':'csv'}
      other_events: {'path':"{base_path}/wiki_example/inputs/{latest}/other_events_log.csv.gz", 'type':'csv'}
    output: {'path':'{base_path}/wiki_example/output_ex5_copy_to_oracle/{now}/', 'type':'csv'}
    copy_to_redshift: {'creds': 'some_redshift_cred_section', 'table': 'sandbox.test_ex5_pyspark_job'}

  examples/ex6_mysql_job.py:  # requires mysql instance running
    api_inputs: {'api_creds': 'some_mysql_cred_section', 'note':'API Job that relies on creds from conf/connections.cfg'}
    output: {'path':'{base_path}/mysql_example/output_ex6_mysql/{now}/', 'type':'csv'}

  job_with_no_output:  # shows job with no output (still requiring table as output but not dumped to disk)
    py_job: 'jobs/examples/ex1_frameworked_job.py'
    inputs:
      some_events: {'path':"{base_path}/wiki_example/inputs/{latest}/events_log.csv.gz", 'type':'csv'}
      other_events: {'path':"{base_path}/wiki_example/inputs/{latest}/other_events_log.csv.gz", 'type':'csv'}
    output: {'path':'n/a', 'type':'None'}

  examples/ex8_koalas_job.py:
    inputs:
      some_events: {'path':"{base_path}/wiki_example/inputs/{latest}/events_log.csv.gz", 'type':'csv'}
      other_events: {'path':"{base_path}/wiki_example/inputs/{latest}/other_events_log.csv.gz", 'type':'csv'}
    output: {'path':'{base_path}/wiki_example/output_ex8_koalas/{now}/', 'type':'csv'}

  examples/ex9_redshift_job.py:
    inputs:
      some_events: {'path':"{base_path}/wiki_example/inputs/{latest}/events_log.csv.gz", 'type':'csv'}
    output: {'path':'{base_path}/wiki_example/output_ex9_redshift/{now}/', 'type':'csv'}
    copy_to_redshift: {'creds': 'some_redshift_cred_section', 'table': 'sandbox.test_ex9_redshift'}

  examples/ex9_mysql_job.py:
    db_inputs: {'creds': 'some_mysql_cred_section', 'note':'API Job that relies on creds from conf/connections.cfg'}
    output: {'path':'{base_path}/wiki_example/output_ex9_mysql/{now}/', 'type':'csv'}

  examples/ex9_mysql_framework_load_job.py:
    inputs:
      some_events: {'type':'mysql', 'db_table': 'some_schema.some_table', 'creds': 'some_mysql_cred_section', 'note':'creds defined in conf/connections.cfg'}
    output: {'path':'{base_path}/wiki_example/output_ex9_mysql_direct/{now}/', 'type':'csv'}

  examples/wordcount_frameworked_job.py:  # shows raw pyspark rdd ops in framework, same as wordcount_raw_job
    inputs:
      lines: {'path':"{base_path}/wordcount_example/input/sample_text.txt", 'type':'txt'}
    output: {'path':'{base_path}/wordcount_example/output_frameworked/{now}/', 'type':'txt'}
    dependencies: [] # list here if any
    frequency: 24h
    owners: ['some_email@address.com']

  # wordcount_raw_job: #Job exists but doesn't rely on jobs_metadata entries

common_params:
  all_mode_params:
    connection_file:  conf/connections.cfg
    redshift_s3_tmp_dir: s3a://dev-spark/tmp_spark/
    email_cred_section: some_email_cred_section  # Section from "connection_file"
  mode_specific_params:
    prod:
      base_path: s3://prod-spark  # don't add '/' at the end
      schema: production
      emr_core_instances: 1
      aws_config_file:  conf/aws_config.cfg
      aws_setup:        dev
      jobs_folder:      jobs/
      load_connectors: all
    EMR_dev:
      base_path: s3://dev-spark  # don't add '/' at the end
      schema: sandbox
      emr_core_instances: 1
      aws_config_file:  conf/aws_config.cfg
      aws_setup:        dev
      jobs_folder:      jobs/
      load_connectors: all
    local_dev:
      base_path: ./data  # don't add '/' at the end
      schema: sandbox
      load_connectors: none
      aws_config_file:  none
